project: deeplearn

paths:
  data_dir: ../data/Hand_Posture_Hard_Stu
  train_data_dir: ../data/Hand_Posture_Hard_Stu
  test_data_dir: ../data/Hand_Posture_Hard_Stu
  output_dir: ./outputs
  model_path: ./model/best_model.pth
  input_model_path: ./model/best_model.pth
  pretrained_weights_path: ./model/resnet50-11ad3fa6.pth

data:
  image_size: 224
  val_ratio: 0.2
  class_names:
    - A
    - B
    - C
    - Five
    - Point
    - V

train:
  epochs: 7
  batch_size: 64
  lr: 0.001
  device: cuda
  progress_interval: 10
  pretrained: true
